openapi: 3.0.0
info:
  title: Reusable Component representing an Akeneo PIM Category
  version: 0.0.1
paths: {}
components:
  schemas:
    akeneo.category:
      allOf:
        - $ref: 'https://raw.githubusercontent.com/rhoepner/openapi-test/master/fock.yaml#/components/schemas/fock.typed'
        - type: object
          description: Akeneo PIM Category
          required: 
            - code
          properties:
            code:
              type: string
          