openapi: 3.0.0
info:
  title: Typed
  version: 0.0.1
paths: {}
components:
  schemas:
    fock.typed:
      type: object
      description: A Typed object within Fock
      required: 
        - schema
      properties:
        schema:
          type: string
    akeneo.category:
      allOf:
        - $ref: '#/components/schemas/fock.typed'
        - type: object
          description: Akeneo PIM Category
          required: 
            - code
          properties:
            code:
              type: string
                    
          