openapi: 3.0.0
info:
  title: fock.Typed
  version: 0.0.1
paths: {}
components:
  schemas:
    fock.Typed:
      type: object
      description: A Typed object within Fock
      required: 
        - schema
      properties:
        schema:
          type: string
