openapi: 3.0.0
info:
  title: Reusable Component representing an Akeneo PIM Category
  version: 0.0.1
paths: {}
components:
  schemas:
    akeneo.Category:
      allOf:
        - $ref: '../fock/Typed.yaml#/components/schemas/fock.Typed'
        - type: object
          description: Akeneo PIM Category
          required: 
            - code
          properties:
            code:
              type: string
          